### ISSUE TITLE
Where do you make your house logos?

### ISSUE THREAD

**Issue by jkevinburton** [thejeffreystone/homeassistant-config#2]
My HA is very much inspired by yours, and I love that you named your houses and even created these icons, how did you come up with them - did you download or draw them yourself?

**Comment by thejeffreystone** [comment]
Hey Kevin!

So the logo of this house I just used part of my Slacker Labs logo that I had created. But usually I look for an image that seems to fit. I am can do a little bit in terms of art, but its not my forte.

**Comment by jkevinburton** [comment]
Gotcha. Thanks. Keep up the awesome content.
